# Generated by Django 2.2.19 on 2022-05-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=50, verbose_name='Кличка котэ')),
                ('breed', models.CharField(max_length=80, verbose_name='Порода котэ')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('owner_name', models.CharField(max_length=50, verbose_name='Имя владельца')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Адрес для браузера')),
                ('info', models.TextField(blank=True, verbose_name='Информация о котэ')),
                ('photo', models.ImageField(upload_to='pics/%Y/', verbose_name='Фото')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
