# Generated by Django 2.2.19 on 2022-05-22 00:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 22, 4, 26, 3, 268667), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='photo',
            field=models.ImageField(upload_to='%Y/', verbose_name='Фото'),
        ),
    ]
