# Generated by Django 2.2.19 on 2022-05-22 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitty', '0002_auto_20220522_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 22, 14, 34, 44, 388375), verbose_name='Дата публикации'),
        ),
    ]
